#Graph 1: Promotion Lift by Country
import pandas as pd
import matplotlib.pyplot as plt


results = pd.read_csv(
    "outputs/country_results.csv"
)


plt.figure(figsize=(10,6))


plt.bar(
    results['country'],
    results['promo_lift_pct']
)


plt.title(
    "Promotion Lift by Country"
)

plt.xlabel(
    "Country"
)

plt.ylabel(
    "Lift (%)"
)


plt.xticks(rotation=45)

plt.tight_layout()


plt.savefig(
    "images/promotion_lift_by_country.png"
)


plt.show()


#Graph 2: Incremental Revenue
plt.figure(figsize=(10,6))


plt.bar(
    results['country'],
    results['avg_incremental_revenue']
)


plt.title(
    "Incremental Revenue Generated by Promotions"
)


plt.xlabel(
    "Country"
)


plt.ylabel(
    "Revenue Impact"
)


plt.xticks(rotation=45)

plt.tight_layout()


plt.savefig(
    "images/incremental_revenue.png"
)


plt.show()

#Graph 3: ATE Comparison
plt.figure(figsize=(10,6))


plt.bar(
    results['country'],
    results['promo_ate_units']
)


plt.title(
    "Average Treatment Effect of Promotions"
)


plt.ylabel(
    "Additional Units Sold"
)


plt.xticks(rotation=45)

plt.tight_layout()


plt.savefig(
    "images/ate_comparison.png"
)


plt.show()

#Graph 4:Placebo Validation

plt.figure(figsize=(8,5))


plt.bar(
    results['country'],
    results['placebo_ate']
)


plt.axhline(
    0
)


plt.title(
    "Placebo Test: Random Treatment Effect"
)


plt.ylabel(
    "Estimated Effect"
)


plt.xticks(rotation=45)


plt.tight_layout()


plt.savefig(
    "images/placebo_validation.png"
)


plt.show()